CREATE TABLE IF NOT EXISTS todos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT,
    content_type TEXT,
    public_type TEXT,
    food_orange INTEGER DEFAULT 0,
    food_apple INTEGER DEFAULT 0,
    food_banana INTEGER DEFAULT 0,
    food_melon INTEGER DEFAULT 0,
    food_grape INTEGER DEFAULT 0,
    category_food INTEGER DEFAULT 0,
    category_drink INTEGER DEFAULT 0,
    category_gadget INTEGER DEFAULT 0,
    category_sport INTEGER DEFAULT 0,
    category_government INTEGER DEFAULT 0,
    category_internet INTEGER DEFAULT 0,
    category_smartphone INTEGER DEFAULT 0,
    country_jp TEXT,
    country_en TEXT,
    prefecture_jp TEXT,
    prefecture_en TEXT,
    created_at TEXT,
    updated_at TEXT
);
